project:
  type: website
  output-dir: docs
  
website:
  site-url: https://www.lisagoetschi.ch/
  title: "Lisa Götschi"
  navbar:
    right:
      - cv.qmd
      - projects.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/lisa-goetschi/
      - icon: github
        href: https://github.com/lisagoetschi
  page-footer:
    background: light 
    left: © 2024-2026, Lisa Götschi 
    right: This website is built with [github](https://github.com/lisagoetschi){target=_blank}, [R](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}

babelquarto:
  languagelinks: navbar
  languagecodes:
  - name: de
    text: "DE"
  - name: en
    text: "EN"
  mainlanguage: 'de'
  languages: ['en']
title-en: Lisa Götschi
lang: de

format:
  html:
    theme: 
    - sandstone
    - styles.scss
    mainfont: Lato
editor: visual

