project:
  type: website
  output-dir: docs
  
website:
  title: ""
  navbar:
    logo: images/Lisa.png
    right:
      - cv.qmd
      - projects.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/lisa-goetschi/
      - icon: github
        href: https://github.com/lisagoetschi
  page-footer:
    background: light 
    left: Copyright 2024, Lisa Götschi 
    right: This website is built with [github](https://github.com/lisagoetschi){target=_blank}, [R](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}

lang: de

format:
  html:
    theme: 
    - sandstone
    - styles.scss
    mainfont: Lato
editor: visual

